# Matrices and Vector Spaces


In this section we look at matrix algebra and some of its common properties. A matrix a is two-dimensional array of numbers. When we do computations with matrices using NumPy, we will be using arrays just as we did before. Let’s write down some of examples of matrices and give them names.







In [1]:
import numpy as np
A = np.array([[1, 3],[2,1]])
B = np.array([[3, 0, 4],[-1, -2, 1]])
C = np.array([[-2, 1],[4, 1]])
D = np.array([[2],[6]])
print(D)

[[2]
 [6]]


It will be useful for us to access the dimensions of our arrays. When the array is created, this information gets stored as part of the array object and can be accessed with a method called 𝚜𝚑𝚊𝚙𝚎
. If 𝙱
 is an array, the object 𝙱.𝚜𝚑𝚊𝚙𝚎
 is itself an array that has two entries. The first (with index 0) is the number of rows, and the second (with index 1) is the number of columns.

In [2]:
print("Array B has",B.shape[0],"rows.")
print("Array B has",B.shape[1],"columns.")  

Array B has 2 rows.
Array B has 3 columns.


# Matrix Algebra

There are three main matrix algerba operations we would like to look at:

1) The multiplication of a number and a matrix:

2) The sum of two matrices of the same shape:

3) The multiplication of two matrices:


These matrix operations are all built into NumPy, but we have to use the symbol @ instead of * for matrix multiplication.

In [3]:
print(3*A,'\n')
print(A+C,'\n')
print(A@B)

[[3 9]
 [6 3]] 

[[-1  4]
 [ 6  2]] 

[[ 0 -6  7]
 [ 5 -2  9]]


# Other Matrix Operations

Another common idea that we will find useful is that of the matrix transpose. The transpose of a matrix 𝐴
is another matrix, 𝐴𝑇, defined so that its columns are the rows of 𝐴. To build 𝐴𝑇, we simple swap the row index with the column index.

In [4]:
A = np.array([[5, 4, 0],[1, 8, 3],[6, 7, 2]])

## Note that the tranpose method must be called with (), the same as a function with no arguments.
A_T = A.transpose()

print(A)
print('\n')
print(A_T)

[[5 4 0]
 [1 8 3]
 [6 7 2]]


[[5 1 6]
 [4 8 7]
 [0 3 2]]


We can also calculate the determinant of a matrix using NumPy with the `np.linalg.det()` command:

In [5]:
# creating a 2X2 Numpy matrix 
n_array = np.array([[50, 29], [30, 44]]) 
  
# Displaying the Matrix 
print("Numpy Matrix is:") 
print(n_array) 
  
# calculating the determinant of matrix 
det = np.linalg.det(n_array) 
  
print("\nDeterminant of given 2X2 matrix:") 
print(int(det))

Numpy Matrix is:
[[50 29]
 [30 44]]

Determinant of given 2X2 matrix:
1330


A similar command exists for the inverse:

In [6]:
x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
print(x) 
print(y) 

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


Checking that multiplying by the inverse gives the identity matrix:

In [7]:
print(x@y)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


Which gives the expected result. To use the identity matrix in Python we use the command `identity` or `eye` - they produce the same result.

In [8]:
arr1 = np.eye(4)
print(arr1)

arr2 = np.identity(5)
print(arr2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


To final useful commands are for calculating the complex conjugate of a matrix `numpy.conjugate()`, and the Hermitian conjugate or adjoint `numpy.matrix.H()`

# Challenge

Create your own 5x5 matrix that includes some elements which are complex numbers. Verify that the Hermitian conjugate is equal to the transpose of the complex conjugate.

In [52]:
import numpy as np

matrix = np.array([
    [1, 2+1j, 3, 4-2j, 5],
    [6-3j, 7, 8, 9+4j, 10],
    [11, 12+5j, 13, 14, 15-6j],
    [16, 17-7j, 18, 19+8j, 20],
])


matrix_conj_T = matrix.conjugate().transpose()

hermitian = np.matrix.getH(matrix) # oh my god this took forever to get, kept throwing errors.

print(matrix_conj_T, "\n \n", hermitian)

[[ 1.-0.j  6.+3.j 11.-0.j 16.-0.j]
 [ 2.-1.j  7.-0.j 12.-5.j 17.+7.j]
 [ 3.-0.j  8.-0.j 13.-0.j 18.-0.j]
 [ 4.+2.j  9.-4.j 14.-0.j 19.-8.j]
 [ 5.-0.j 10.-0.j 15.+6.j 20.-0.j]] 
 
 [[ 1.-0.j  6.+3.j 11.-0.j 16.-0.j]
 [ 2.-1.j  7.-0.j 12.-5.j 17.+7.j]
 [ 3.-0.j  8.-0.j 13.-0.j 18.-0.j]
 [ 4.+2.j  9.-4.j 14.-0.j 19.-8.j]
 [ 5.-0.j 10.-0.j 15.+6.j 20.-0.j]]


# References

https://bvanderlei.github.io/jupyter-guide-to-linear-algebra/Matrix_Algebra.html


# Research

Solving for spin in a general direction is something that we had to do for Quantum Mechanics and beause for whatever reason I seem to like pain, I will go ahead and try to do it using sympy. The general idea is that we have a matrix operator S which we will use to solve for the eigenvalues of the |+> ket and |-> ket to find out to try and get an equation for spin in a general direction. Once the eigenvalues are solved for I need to solve for the eigenvectors which will give the equation of |+>n = a|+> + b|-> and |->n = a|+> - b|-> where a and b are the values from the eigenvector. That was confusing, quantum is confusing. Life is pain.

So, I went ahead and did this below and got something close to the correct answer minus some trig substitutions to making things look prettier. You can seem me just throwing in .applyfunc(trigsimp) to try and mitigate this but it's not working. I need to delve further into the code to find out if it's possible or have to simplify manually, which is no fun. Also, something to keep in mind is basically being able to throw away the e^(i*phi) because it's physically just a phase change which is not a concern. 

In conclusion, eigenvalues and eigenvectors are a fundamental part of quantum mechanics where everything is multidimensional and systems of multidimensional things that are rarely linearly dependent.

In [12]:
import sympy as sym
from sympy import symbols, Matrix, I, sqrt, Abs, simplify, trigsimp, pprint

# Define symbols
x, y, h = symbols("x y h", real=True) 

# Create the 2x2 matrix operator
S_n_operator = (h/2) * Matrix([
    [sym.cos(x), sym.sin(x) * sym.exp(-I * y)],
    [sym.sin(x) * sym.exp(I * y), -sym.cos(x)]
])

# Pretty print the operator
print("Our Operator:")
pprint(S_n_operator)
print("\n")

# Solve for eigenvalues of the operator
eigenvalues = S_n_operator.eigenvals()

# Pretty print the eigenvalues
print("Operator Eigenvalues:")
pprint(eigenvalues)
print("\n")

# Solve for eigenvectors
eigenvectors = S_n_operator.eigenvects()
# orthogonality = eigenvectors[0] * eigenvectors[1]

# Function to normalize a vector and simplify the result
def normalize(vec):
    norm = sqrt(sum([Abs(element)**2 for element in vec]))
    normalized_vec = vec / norm
    # Apply simplify and trigsimp for simplification
    return normalized_vec.applyfunc(trigsimp).applyfunc(simplify)

# Loop over each eigenvalue and its corresponding eigenvectors
for eigenvalue_info in eigenvectors:
    eigenvalue = eigenvalue_info[0]
    multiplicity = eigenvalue_info[1]
    eigenvector_list = eigenvalue_info[2]
    
    # For each eigenvector associated with this eigenvalue
    for vec in eigenvector_list:
        normalized_vec = normalize(vec).applyfunc(trigsimp)
        print(f"Eigenvalue: {eigenvalue}")
        print("Normalized Eigenvector:")
        pprint(normalized_vec.applyfunc(trigsimp))
        print("\n")


Our Operator:
⎡                  -ⅈ⋅y       ⎤
⎢  h⋅cos(x)     h⋅ℯ    ⋅sin(x)⎥
⎢  ────────     ──────────────⎥
⎢     2               2       ⎥
⎢                             ⎥
⎢   ⅈ⋅y                       ⎥
⎢h⋅ℯ   ⋅sin(x)    -h⋅cos(x)   ⎥
⎢─────────────    ──────────  ⎥
⎣      2              2       ⎦


Operator Eigenvalues:
⎧-h      h   ⎫
⎨───: 1, ─: 1⎬
⎩ 2      2   ⎭


Eigenvalue: -h/2
Normalized Eigenvector:
⎡            -ⅈ⋅y               ⎤
⎢       -√2⋅ℯ    ⋅sin(x)        ⎥
⎢───────────────────────────────⎥
⎢                   ____________⎥
⎢                  ╱     1      ⎥
⎢2⋅(cos(x) + 1)⋅  ╱  ────────── ⎥
⎢               ╲╱   cos(x) + 1 ⎥
⎢                               ⎥
⎢              √2               ⎥
⎢      ──────────────────       ⎥
⎢            ____________       ⎥
⎢           ╱     1             ⎥
⎢      2⋅  ╱  ──────────        ⎥
⎣        ╲╱   cos(x) + 1        ⎦


Eigenvalue: h/2
Normalized Eigenvector:
⎡            -ⅈ⋅y               ⎤
⎢       -√2⋅ℯ    ⋅sin(x)        ⎥
